import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const bb = process.env.BB_CLI || "bb";

const [galleryCss, atlasTokens] = await Promise.all([
  readFile(resolve(packageRoot, "gallery.css"), "utf8"),
  readFile(resolve(packageRoot, "atlas-ds/tokens.css"), "utf8"),
]);
const pluginCustomCss = `@scope ([data-bb-plugin-root]) {\n${atlasTokens.trim()}\n\n${galleryCss.trim()}\n}\n`;
await writeFile(
  resolve(packageRoot, "plugin-styles.ts"),
  `// Generated by scripts/build.mjs from the Atlas DS tokens and gallery styles.\nexport const atlasPluginStyles = ${JSON.stringify(pluginCustomCss)};\n`,
);

const result = spawnSync(bb, ["plugin", "build", packageRoot], {
  cwd: packageRoot,
  stdio: "inherit",
});

if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
